"""
Generate reference vectors for Fisher's exact test using SciPy.

This is intended as a one-time (or occasional) helper for updating the test
fixtures without requiring SciPy at test/runtime.

Usage:
  python scripts/generate_fisher_expected.py > tests/fisher_vectors.py
"""

from __future__ import annotations

import math
import random

from scipy import stats


def _case(table):
    result = stats.fisher_exact(table)
    return {
        "table": table,
        "odds_ratio": float(result.statistic),
        "p_value": float(result.pvalue),
    }


def _py_float(value: float) -> str:
    if math.isnan(value):
        return "math.nan"
    if math.isinf(value):
        return "math.inf" if value > 0 else "-math.inf"
    return repr(value)


def _py_case(case: dict) -> str:
    table = case["table"]
    return (
        "{"
        f"\"table\": {table}, "
        f"\"odds_ratio\": {_py_float(case['odds_ratio'])}, "
        f"\"p_value\": {_py_float(case['p_value'])}"
        "}"
    )


def main() -> None:
    cases = []

    curated = [
        [[0, 1], [1, 0]],
        [[0, 2], [3, 0]],
        [[1, 0], [0, 1]],
        [[10, 0], [0, 10]],
        [[8, 2], [1, 5]],
        [[1, 9], [11, 3]],
        [[2, 7], [8, 2]],
        [[7, 1], [1, 7]],
        [[3, 3], [3, 3]],
        [[4, 6], [7, 3]],
        [[6, 4], [3, 7]],
        [[0, 5], [0, 10]],
        [[5, 0], [10, 0]],
        [[0, 5], [10, 0]],
        [[5, 5], [5, 5]],
        [[9, 1], [1, 9]],
        [[12, 3], [4, 14]],
        [[1, 2], [3, 4]],
        [[2, 1], [4, 3]],
        [[2, 2], [2, 2]],
        [[0, 7], [6, 5]],
        [[7, 0], [5, 6]],
        [[4, 0], [1, 9]],
        [[0, 4], [9, 1]],
        [[15, 5], [20, 30]],
        [[20, 30], [15, 5]],
        [[100, 1], [1, 100]],
        [[1, 100], [100, 1]],
        [[0, 20], [5, 5]],
        [[20, 0], [5, 5]],
    ]
    for table in curated:
        cases.append(_case(table))

    rng = random.Random(1337)
    for _ in range(60):
        while True:
            table = [[rng.randint(0, 25), rng.randint(0, 25)] for _ in range(2)]
            if sum(sum(r) for r in table) > 0:
                break
        cases.append(_case(table))

    print("# Generated by scripts/generate_fisher_expected.py")
    print("# Do not edit by hand; re-run the generator.")
    print("")
    print("import math")
    print("")
    print("FISHER_EXACT_VECTORS = [")
    for case in cases:
        print("  " + _py_case(case) + ",")
    print("]")


if __name__ == "__main__":
    main()
